Import("*")

SimObject("BaseVTA.py", sim_objects=["BaseVTA"])

Source("base_vta.cc")
Source("buffer.cc")
Source("compute_module.cc")
Source("data_queue.cc")
Source("instruction_fetch_module.cc")
Source("instruction_queue.cc")
Source("load_module.cc")
Source("store_module.cc")

DebugFlag("BaseVTAFlag")
