Import("*")

SimObject("BaseVTA.py", sim_objects=["BaseVTA"])
SimObject("ComputerModule.py", sim_objects=["ComputerModule"])
SimObject("InstructionFetchModule.py", sim_objects=["InstructionFetchModule"])
SimObject("Buffer.py", sim_objects=["Buffer"])
SimObject("InstructionQueue.py", sim_objects=["InstructionQueue"])
SimObject("DataQueue.py", sim_objects=["DataQueue"])
SimObject("LoadModule.py", sim_objects=["LoadModule"])
SimObject("StoreModule.py", sim_objects=["StoreModule"])


Source("base_vta.cc")
Source("buffer.cc")
Source("computer_module.cc")
Source("core_module.cc")
Source("data_queue.cc")
Source("instruction_fetch_module.cc")
Source("instruction_queue.cc")
Source("load_module.cc")
Source("store_module.cc")

DebugFlag("BaseVTAFlag")
